//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaralDemo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Documents_BankDetails
    {
        public int DocID { get; set; }
        public int EmployeeID { get; set; }


        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Please enter Aadhar Card")]
        [RegularExpression(@"^[2-9]{1}[0-9]{11}$", ErrorMessage = "Please Enter In Pateern Like:36759834601")]
        public long AadharCard { get; set; }


        [Required(ErrorMessage = "Please enter Pan Card")]
        [RegularExpression(@"[A-Z]{5}[0-9]{4}[A-Z]{1}", ErrorMessage = "Please Enter Valid PanNumber")]
        public string PanCard { get; set; }


        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Please Enter PF Accno")]
        [RegularExpression(@"^\d{9,18}$", ErrorMessage = "The bank should have 9-18 digits")]
        public Nullable<int> PfAccNo { get; set; }



        [Required(ErrorMessage = "Please enter Bank Name")]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Use Only Characters And Space is not Allowed")]
        public string BankName { get; set; }


        [Required(ErrorMessage = "Please enter Branch Name")]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Use Only Characters And Space is not Allowed")]
        public string BranchName { get; set; }


        [DataType(DataType.Text)]
        [RegularExpression(@"^[A-Z]{4}0[A-Z0-9]{6}$", ErrorMessage = "Please Enter Valid Ifsc Code")]
        [Required(ErrorMessage = "Please enter Ifsc Code")]
        public string IfscCode { get; set; }


        [DataType(DataType.Text)]
        [RegularExpression(@"^\d{9,18}$", ErrorMessage = "The bank should have 9-18 digits")]
        [Required(ErrorMessage = "Please Enter Bank AccNo")]
        public Nullable<long> BankAccNo { get; set; }

        public virtual Employee Employee { get; set; }
    }
}
