//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaralDemo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Leave_Request
    {
        public int LeaveID { get; set; }

        [Display(Name = "Employee Name")]
        public int EmployeeID { get; set; }

        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "From Date")]
        [Required(ErrorMessage = "Please enter FromDate")]
        public Nullable<System.DateTime> FromDate { get; set; }


        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "To Date")]
        public Nullable<System.DateTime> ToDate { get; set; }

        [Display(Name = "Leave Type")]
        [Required(ErrorMessage = "Please enter LeaveType")]
        public int LeaveType { get; set; }


        [DataType(DataType.MultilineText)]
        [Required(ErrorMessage = "Please enter ReasonOfLeave")]
        [Display(Name = "Reason Of Leave")]
        public string ReasonOfLeave { get; set; }

        [Required(ErrorMessage = "Please enter Half Day")]
        [Display(Name = "Half Day")]
        public string HalfDay { get; set; }

        [Required(ErrorMessage = "Please enter Full Day")]
        [Display(Name = "Full Day")]
        public string FullDay { get; set; }

        [Display(Name = "Leave Status")]
        public string LeaveStatus { get; set; }

        [DataType(DataType.Text)]
        public Nullable<decimal> TotalDays { get; set; }

        public virtual Employee Employee { get; set; }
    }
}
