//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaralDemo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Employee_Management_SystemEntities : DbContext
    {
        public Employee_Management_SystemEntities()
            : base("name=Employee_Management_SystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<LeaveType> LeaveTypes { get; set; }
        public virtual DbSet<Salary_Slip> Salary_Slip { get; set; }
        public virtual DbSet<Documents_BankDetails> Documents_BankDetails { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<TechnicalDetail> TechnicalDetails { get; set; }
        public virtual DbSet<Leave_Request> Leave_Request { get; set; }
        public virtual DbSet<LeaveCount> LeaveCounts { get; set; }
    }
}
