//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaralDemo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TechnicalDetail
    {
        public int TechID { get; set; }
        public int EmployeeID { get; set; }


        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Please enter Total Years Of Experience")]
        [RegularExpression(@"^(?:1?\d(?:\.\d{1,2})?|20(?:\.0?0?)?)$", ErrorMessage = "Invalid Input")]
        public Nullable<decimal> TotalYearsOfExperience { get; set; }


        [Required(ErrorMessage = "Please enter Known Technologiies")]
        public string KnownTechnologiies { get; set; }


        [RegularExpression(@"^[a-zA-Z\s]+$", ErrorMessage = "Use Only Characters")]
        [Required(ErrorMessage = "Please enter Education Details")]
        public string Education { get; set; }


        [RegularExpression(@"^((\d*[1-9]+\d*(\.\d+)?)|(\d*\.\d*[1-9]+\d*))$", ErrorMessage = "Invalid Input")]
        [Required(ErrorMessage = "Please enter Previous CTC")]
        public Nullable<decimal> PreviousCTC { get; set; }


        [RegularExpression(@"^((\d*[1-9]+\d*(\.\d+)?)|(\d*\.\d*[1-9]+\d*))$", ErrorMessage = "Invalid Input")]
        [Required(ErrorMessage = "Please enter CureentCTC")]
        public Nullable<decimal> CureentCTC { get; set; }

        public virtual Employee Employee { get; set; }
    }
}
